# Metadata of how many galleries can be requested before mandatory cooldown.
antispam:
  room:
    max: 10
    delay: 60
  user:
    max: 5
    delay: 60

# Set it to false to make the bot send gallery thumbnails separately from metadata.
# Responses to messages linking to more than 2 distinct galleries will inline thumbnails regardless of this setting.
inline_thumbs: true
